---
core:
    num_workers: 10


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "/RESTCONF/hosts.yaml"
        group_file: "/RESTCONF/groups.yaml"
        defaults_file: "/RESTCONF/defaults.yaml"
